use std::fs;
use std::path::Path;

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let migrations_dir = Path::new("migrations");

    if !migrations_dir.exists() {
        // 无 migrations 目录时生成空数组（Docker 构建阶段未 COPY 时）
        let code = "// AUTO-GENERATED by build.rs — DO NOT EDIT\npub const MIGRATIONS: &[(&str, &str)] = &[];\n";
        fs::write(Path::new(&out_dir).join("embedded_migrations.rs"), code).unwrap();
        return;
    }

    let mut files: Vec<_> = fs::read_dir(migrations_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "sql"))
        .filter(|e| {
            let name = e.file_name().to_string_lossy().to_string();
            // 初始 schema 由 models/mod.rs 的 include_str! 单独处理
            !name.starts_with("0000000000_")
        })
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();

    files.sort();

    let abs_dir = migrations_dir.canonicalize().unwrap();
    let mut code = String::from(
        "// AUTO-GENERATED by build.rs — DO NOT EDIT\npub const MIGRATIONS: &[(&str, &str)] = &[\n",
    );

    for f in &files {
        let abs_path = abs_dir.join(f);
        code.push_str(&format!(
            "    (\"{}\", include_str!(r\"{}\")),\n",
            f,
            abs_path.to_str().unwrap()
        ));
    }

    code.push_str("];\n");

    fs::write(Path::new(&out_dir).join("embedded_migrations.rs"), code).unwrap();
    println!("cargo:rerun-if-changed=migrations/");
}
