/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/front/ActionBar.vue')['default']
    AdminLayout: typeof import('./components/admin/AdminLayout.vue')['default']
    AiChatWidget: typeof import('./components/shared/AiChatWidget.vue')['default']
    CodeCopyWrapper: typeof import('./components/shared/CodeCopyWrapper.vue')['default']
    FriendLinks: typeof import('./components/front/FriendLinks.vue')['default']
    FrontLayout: typeof import('./components/front/FrontLayout.vue')['default']
    GuestbookFormModal: typeof import('./components/shared/GuestbookFormModal.vue')['default']
    ImageSelector: typeof import('./components/shared/ImageSelector.vue')['default']
    NavBar: typeof import('./components/shared/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NUpload: typeof import('naive-ui')['NUpload']
    PostCard: typeof import('./components/shared/PostCard.vue')['default']
    PostSettingsModal: typeof import('./components/shared/PostSettingsModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarCard: typeof import('./components/front/SidebarCard.vue')['default']
    TagCloud: typeof import('./components/front/TagCloud.vue')['default']
    VditorEditor: typeof import('./components/admin/VditorEditor.vue')['default']
    WebmasterInfo: typeof import('./components/front/WebmasterInfo.vue')['default']
  }
}
